version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: intelligence_postgres
    environment:
      POSTGRES_DB: intelligence
      POSTGRES_USER: intelligence_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-intelligence_pass}
    volumes:
      - ../../data/postgres:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: intelligence_redis
    volumes:
      - ../../data/redis:/data
    ports:
      - "127.0.0.1:6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
